### ISSUE TITLE
hard to make interactive heatmap because rownames can't be duplicated 

### ISSUE THREAD

**Issue by Stomper2008** [MartinBrown2000/waste-impact-calculator#14]
before you can run the heatmaply code, you have to have a set of unique rownames?

i can't seem to generate this.  but it is late.

**Comment by MartinBrown2000** [comment]
Solved -- though it turned out to be more of a pain than one would have thought.
It's very difficult to add row names to a reactive matrix.  I couldn't figure it out.
But I can save the row names to a string, and then make a heat map with d3heatmap.  Note for shiny it has its own render and output functions

**Comment by MartinBrown2000** [comment]
actually, never mind!!!! you can use labRow in heatmaply as well!!!!
